import AuthProvider from '@/contexts/auth-provider'
import 'easymde/dist/easymde.min.css'
import NavBar from '@/components/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <header className="sticky top-0 bg-primary-foreground">
        <NavBar />
      </header>
      <section className="container">
        <main>{children}</main>
      </section>
    </AuthProvider>
  )
}
